name: image_form_field
description: Upload images in Flutter forms
version: 0.0.2
homepage: https://github.com/tshedor/flutter_image_form_field
author: Tim Shedor <opensource@timshedor.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.4.10
